version: "3"
services:
  postgres:
    image: demo-postgres
    ports:
      - "5432:5432"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
  redis:
    image: bitnami/redis:7.0.2
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
  jaeger:
    image: jaegertracing/all-in-one:1.35.2
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: "true"
  prometheus:
    image: prom/prometheus:v2.36.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-enterprise:9.0.1
    ports:
      - "3000:3000"
  otel-demo-provider:
    image: otel-demo-provider
    ports:
      - "8080:8080"
      - "9463:9464"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JAVA_OPTS: -javaagent:/agent/opentelemetry-javaagent.jar
      DEST_URL: https://httpbin.org/get
      OTEL_PROPAGATORS: b3multi
      OTEL_TRACES_EXPORTER: zipkin,logging
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: http://jaeger:9411/api/v2/spans
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_HOST: otel-demo-provider
      OTEL_EXPORTER_PROMETHEUS_PORT: 9464
      OTEL_TRACES_SAMPLER_ARG: 1
      OTEL_TRACES_SAMPLER: parentbased_always_on
      OTEL_RESOURCE_ATTRIBUTES: service.name=otel-demo-provider
    volumes:
      - ./agent/opentelemetry-javaagent.jar:/agent/opentelemetry-javaagent.jar
    restart: always
    depends_on:
      - postgres
      - redis
  otel-demo-consumer:
    image: otel-demo-consumer
    ports:
      - "8081:8081"
      - "9464:9464"
    environment:
      SERVICE_HOST: otel-demo-provider
      JAVA_OPTS: -javaagent:/agent/opentelemetry-javaagent.jar
      OTEL_PROPAGATORS: b3multi
      OTEL_TRACES_EXPORTER: zipkin,logging
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: http://jaeger:9411/api/v2/spans
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_PROMETHEUS_HOST: otel-demo-consumer
      OTEL_EXPORTER_PROMETHEUS_PORT: 9464
      OTEL_TRACES_SAMPLER_ARG: 1
      OTEL_TRACES_SAMPLER: parentbased_always_on
      OTEL_RESOURCE_ATTRIBUTES: service.name=otel-demo-consumer
    volumes:
      - ./agent/opentelemetry-javaagent.jar:/agent/opentelemetry-javaagent.jar
    restart: always
    depends_on:
      - otel-demo-provider