# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["prometheus:9090", "otel-demo-consumer:9464", "otel-demo-provider:9464"]

#
#remote_write:
#  - url: http://prometheus:9090/api/v1/write
#    remote_timeout: 30s
#    tls_config:
#      insecure_skip_verify: true
#    queue_config:
#      capacity: 500
#      max_shards: 1000
#      min_shards: 1
#      max_samples_per_send: 100
#      batch_send_deadline: 5s
#      min_backoff: 30ms
#      max_backoff: 100ms